version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./app/:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: 
      - .env

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_SCHEMA}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - ./postgres_migrations:/docker-entrypoint-initdb.d  # path for migration scripts

volumes:
  postgres_data:
