// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Todo struct {
	Uuid        uuid.UUID
	Title       string
	Description sql.NullString
	Done        bool
	BoardUuid   uuid.NullUUID
}
