run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  enable:
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - ineffassign

issues:
  max-same-issues: 3
  max-issues-per-linter: 50
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
